[theme]
primaryColor = "#4cc9f0"
# backgroundColor = "#0b1220"
backgroundColor = "#111111"
# secondaryBackgroundColor = "#151e31"
secondaryBackgroundColor = "#393939"
textColor = "#e9eef5"
font = "sans serif"

[server]
enableStaticServing = true
